# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to AWS
on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    environment: s3-access
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: yarn
    - name: Build React Package
      run: CI=false yarn build
    - name: Upload to S3
      uses: reggionick/s3-deploy@v3
      with:
        # aws bucket name
        bucket: www.condution.com
        # directory to upload
        folder: build
        # bucket location
        bucket-region: us-east-2
